version: '3.9'

services:
  GameChallenge.web:
    #image: ${DOCKER_REGISTRY-}GameChallengeweb    
    image: addu143/GameChallengeweb:latest
    build:
      context: .
      dockerfile: GameChallenge.Web/Dockerfile
    volumes: 
    - shared-folder:/app/sqllite
volumes:
 shared-folder:
    external: false
  #sqldata:
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  environment:
  #    - SA_PASSWORD=vV5r9tn0M4@
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "1450:1433"
   